version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: repko
      POSTGRES_PASSWORD: repko
      POSTGRES_DB: repko
    ports:
      - "5432:5432"
    volumes:
      - repko_postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: repko
      MINIO_ROOT_PASSWORD: repko123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - repko_minio:/data

volumes:
  repko_postgres:
  repko_minio:
